site_name: Notas Musicais
repo_url: https://github.com/cesarfreire/notas-musicais
repo_name: cesarfreire/notas-musicais
edit_uri: tree/main/docs


theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

dev_addr: '127.0.0.1:8080'
markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css